# Generated by Django 5.1.6 on 2025-02-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ativo', models.BooleanField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
